# Change these first
owner: reinhart1010 # Your GitHub organization or username, where this repository lives
repo: binusmayadown # The name of this repository

sites:
  - name: BINUSMAYA (Homepage)
    url: https://binusmaya.binus.ac.id
  - name: BINUSMAYA (Academic Services)
    url: https://acadservices.apps.binus.ac.id/LoginAD.php
  - name: BINUSMAYA (Learning Management System)
    url: https://newbinusmaya.binus.ac.id
  - name: BINUSMAYA (Parent)
    url: https://parent.binus.ac.id
  - name: BINUS Mobile (Server 1)
    url: https://mobileapi.apps.binus.edu
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: BINUS Mobile (Server 2)
    url: https://mobileapi2.apps.binus.edu
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: BINUSMAYA Exam
    url: https://exam.apps.binus.ac.id
  - name: BINUSMAYA Exam - Multiple Choice
    url: https://socs1.binus.ac.id/tcexam/public/code/index.php
  - name: BINUSMAYA CDN (newcontent.binus.ac.id)
    url: https://newcontent.binus.ac.id
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: BINUSMAYA CDN (bm5cdn.azureedge.net)
    url: https://bm5cdn.azureedge.net
    expectedStatusCodes:
      - 200
      - 201
      - 400
  - name: Admission Online Frontend (AOF) 3 (BINUSIAN 2024 and below)
    url: https://admissions.apps.binus.edu/admissions
  - name: Admission Online Frontend (AOF) 4 (BINUSIAN 2025 and up)
    url: https://newadmissions.apps.binus.edu/admissions
  - name: Course Enrollment and Registration (bcs.binus.ac.id)
    url: http://bcs.binus.ac.id
  - name: BINUSMAYA Praktikum (SLC Bluejack)
    url: https://bluejack.binus.ac.id/binusmayalab/
  - name: SLC Laboratory (laboratory.binus.ac.id)
    url: https://laboratory.binus.ac.id/lab
  - name: SLC Remote Lab (rlab.binus.ac.id)
    url: https://rlab.apps.binus.ac.id/
  - name: Laboratory Borrowing (labfacility.apps.binus.ac.id)
    url: https://labfacility.apps.binus.ac.id/
  - name: Library and Knowledge Center (LKC)
    url: http://library.binus.ac.id
  - name: GreatNusa.com
    url: https://greatnusa.com
  - name: BINUS CX (Class eXtension)
    url: https://cx.apps.binus.ac.id
    __dangerous__insecure: true
  - name: BINUS Store
    url: https://binusstore.com
  - name: BISANARA
    url: https://bisanara.com
  - name: BINUS Entrepreneurship (BEC) Apps
    url: https://entrepreneurship.apps.binus.ac.id
  - name: Teach For Indonesia (TFI) APPS
    url: https://tfi.apps.binus.ac.id/
  - name: Enrichment Apps
    url: https://enrichment.apps.binus.ac.id
  - name: Activity Enrichment Apps
    url: https://activity-enrichment.apps.binus.ac.id
  - name: Internship Apps
    url: https://internship.apps.binus.ac.id
  - name: Apple Developer Academy Apps
    url: https://developeracademy.apps.binus.ac.id
  - name: Research Apps
    url: https://research.apps.binus.ac.id
  - name: Student Certification Apps
    url: http://studentcertification.apps.binus.ac.id
  - name: Thesis Apps
    url: https://thesis.apps.binus.ac.id
  - name: BINUS Career
    url: https://binuscareer.com
  - name: BISANARA
    url: https://bisanara.com
  - name: School of Computer Science Competitive Programming Quiz
    url: https://socs1.binus.ac.id/quiz/public/
  - name: BINUSIAN Blog
    url: http://blog.binusian.org
  - name: BINUS Youth Festival (BYFest)
    url: https://student.binus.ac.id/byfest
  - name: Competitive Programming Competitions - Homepage
    url: https://competition.binus.ac.id/portal/
  - name: Competitive Programming Competitions - DOMJudge Instance
    url: https://competition.binus.ac.id/contest/public
  - name: Scribees
    url: https://binus.ac.id/scribees/login/
  - name: Collabees
    url: https://dmd.binus.ac.id/collabees/
  - name: Vairbees (Virtual Expo)
    url: https://vairbees.binus.edu
  - name: BINUS Graduate Attribute Assessment Apps
    url: https://bga.apps.binus.ac.id/
  - name: BINUS Integrated Survey Reporting Application (ISRA) (qmc.apps.binus.ac.id)
    url: https://qmc.apps.binus.ac.id/isra
  - name: BINUS ISRA API Server 1
    url: https://qmc.apps.binus.ac.id/api/v1/loadSetting
  - name: BINUS ISRA API Server 2
    url: https://qmcapi2.apps.binus.ac.id/isra/api

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: binusmayadown.reinhart1010.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BINUSMAYA Down
  introTitle: "**World Class University pun bisa down.** Kalau kamu?"
  introMessage: |
    Di sini Anda bisa memonitor apakah para server di balik ["Semesta Aplikasi BINUS"](https://newbinusmaya.binus.ac.id) sedang down atau tidak. Situs ini tidak terafiliasi, terasosiasi, atau terhubung dalam bentuk apapun dengan [Universitas BINA NUSANTARA](https://binus.ac.id) dan [Yayasan Pendidikan BINA NUSANTARA](https://binus.edu).
    <br><br>
    <b>&copy; 2022 [Reinhart Previano Koentjoro](https://reinhart1010.id).</b> Anda kini bisa mendukung saya untuk membayar biaya operasional untuk situs ini dan [BINUSToday](https://binustoday.reinhart1010.id) melalui [Karyakarsa](https://karyakarsa.id/reinhart1010), [Saweria](https://saweria.com/reinhart1010), dan [Trakteer](https://trakteer.id/reinhart1010).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
